; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
description = "наш первый проект по последнему релизу ёрадио"
extra_configs = 
	config_DevBoard_ESP32_Wrover-kit.ini
	config_DevBoard_ESP32_S3-kit.ini

;default_envs = esp32-wrover-kit
default_envs = esp32-s3-kit

[common]
build_flags = 
	-D VERSION=0.0.1
  -D CORE_DEBUG_LEVEL=3
  -Iconfig          ; ← добавляет папку config (в ней настройки пинов)/ в пути поиска

[env]
framework = arduino
platform = espressif32
board = esp-wrover-kit

;board_build.filesystem = littlefs  ;в этом проекте не пашет (Поддерживает каталоги)
;board_build.filesystem = SPIFFS    ;а с этим пашет (по умолчанию уже стоит) (Не поддерживает каталоги)
;upload_speed = 115200
upload_speed = 921600 ;115200 ;

monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0
monitor_filters = esp32_exception_decoder, time
monitor_echo = yes

;файл русского шрифта
;взять отсюда
; ...\yoRadio_Wrover_S3\src\fonts\glcdfont.c
;положить сюда
; ...\yoRadio_Wrover_S3\src\src\Adafruit_GFX_Library\glcdfont.c

;редактор тем для дисплея для файла mytheme.h
;https://vip-cxema.org/index.php/online-kalkulyatory/yoradio-redaktor-tem



;Полезные команды PlatformIO:
;bash (терминал)
;pio run --target clean   # сбросить кеш
;pio run                  # пересобрать

;pio run -t upload        # Загрузка кода
;pio run -t uploadfs      # Загрузка файлов в SPIFFS
;pio run -t monitor       # Монитор порта
;esptool erase_flash

;git commit -m "Ваше сообщение об изменениях"
;git add config_DevBoard_ESP32_S3-kit.ini