; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
description = "наш первый проект по последнему релизу ёрадио"
extra_configs = 
	config_DevBoard_ESP32_Wrover-kit.ini
	config_DevBoard_ESP32_S3-kit.ini

default_envs = esp32-wrover-kit
;default_envs = esp32-s3-kit

[common]
build_flags = 
	-D VERSION=0.0.1
  -D CORE_DEBUG_LEVEL=3
  -Iconfig          ; ← добавляет папку config (в ней настройки пинов)/ в пути поиска
  -D_IR_ENABLE_DEFAULT_=false
    -DDECODE_NEC=true
    -DNDEBUG  # Отключить отладочные сообщения

build_src_filter = 
    +<*> 
    -<src/src/displays/displayGC9106.cpp>
    -<src/src/displays/displayGC9A01A.cpp>
    -<src/src/displays/displayILI9225.cpp>
    -<src/src/displays/displayILI9488.cpp>
    -<src/src/displays/displayLC1602.cpp>
    -<src/src/displays/displayN5110.cpp>
    -<src/src/displays/displaySH1106.cpp>
    -<src/src/displays/displaySSD1305.cpp>
    -<src/src/displays/displaySSD1306.cpp>
    -<src/src/displays/displaySSD1322.cpp>
    -<src/src/displays/displaySSD1327.cpp>
    -<src/src/displays/displayST7735.cpp>
    -<src/src/displays/displayST7789.cpp>
    -<src/src/displays/displayST7796.cpp>
    -<src/src/displays/displayST7920.cpp>
    -<src/src/displays/nextion.cpp>
    -<src/src/audioVS1053/audioVS1053Ex.cpp>

[env]
framework = arduino
platform = espressif32
board = esp-wrover-kit




;board_build.filesystem = littlefs  ;в этом проекте не пашет (Поддерживает каталоги)
;board_build.filesystem = SPIFFS    ;а с этим пашет (по умолчанию уже стоит) (Не поддерживает каталоги)
;upload_speed = 115200
upload_speed = 921600 ;115200 ;

monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0
monitor_filters = esp32_exception_decoder, time
monitor_echo = yes




;файл русского шрифта
;взять отсюда
; ...\yoRadio_Wrover_S3\src\fonts\glcdfont.c
;положить сюда
; ...\yoRadio_Wrover_S3\src\src\Adafruit_GFX_Library\glcdfont.c

;редактор тем для дисплея для файла mytheme.h
;https://vip-cxema.org/index.php/online-kalkulyatory/yoradio-redaktor-tem



;Полезные команды PlatformIO:
;bash (терминал)
;pio run --target clean   # сбросить кеш
;pio run                  # пересобрать

;pio run -t upload        # Загрузка кода
;pio run -t uploadfs      # Загрузка файлов в SPIFFS
;pio run -t monitor       # Монитор порта
;esptool erase_flash

;git commit -m "Ваше сообщение об изменениях"
;git add config_DevBoard_ESP32_S3-kit.ini