; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
description = "наш первый проект по последнему релизу ёрадио"
extra_configs = 
	config/env/config_DevBoard_ESP32_Wrover-kit.ini
	config/env/config_DevBoard_ESP32_S3-kit.ini

default_envs = esp32-wrover-kit
;default_envs = esp32-s3-kit

[common]
;это просто любое имя (здесь - custom common options) общий блок для всего проекта (это называется Interpolation of Values)
;можно Общие флаги компиляции (build_flags =), Базовые зависимости, общие для всех плат (lib_deps_builtin =, lib_deps_external = ),Пути к общим библиотекам (lib_extra_dirs =)
;нельзя указывать platform, board, framework — это параметры конкретной среды. 
build_flags = 
	-DVERSION=0.0.1
    -DCORE_DEBUG_LEVEL=3
    -Iconfig          ;ищем файлы *.ini *.h здесь ← добавляет папку config (в ней настройки пинов)/ в пути поиска
;    -Iconfig/locale   ;ищем файлы *.h здесь
    -Iinclude/locale         ;ищем файлы *.h здесь
    -D_IR_ENABLE_DEFAULT_=false
 ;   -DDECODE_NEC=true
    -DNDEBUG  # Отключить отладочные сообщения

;исключить лишние файлы из сборки
build_src_filter = 
    +<*> 
    -<displays/displayGC9106.cpp>
    -<displays/displayGC9A01A.cpp>
    -<displays/displayILI9225.cpp>
    -<displays/displayILI9488.cpp>
    -<displays/displayLC1602.cpp>
    -<displays/displayN5110.cpp>
    -<displays/displaySH1106.cpp>
    -<displays/displaySSD1305.cpp>
    -<displays/displaySSD1306.cpp>
    -<displays/displaySSD1322.cpp>
    -<displays/displaySSD1327.cpp>
    -<displays/displayST7735.cpp>
    -<displays/displayST7789.cpp>
    -<displays/displayST7796.cpp>
    -<displays/displayST7920.cpp>
    -<displays/nextion.cpp>

    -<audioVS1053/audioVS1053Ex.cpp>

    -<IRremoteESP8266/*>
   ; +<src/IRremoteESP8266/IRac.cpp>
    +<IRremoteESP8266/IRrecv.cpp>
    +<IRremoteESP8266/IRsend.cpp>
    +<IRremoteESP8266/IRtext.cpp>
    +<IRremoteESP8266/IRtimer.cpp>
    +<IRremoteESP8266/IRutils.cpp>
    +<IRremoteESP8266/ir_NEC.cpp>

    -<Adafruit_GFX_Library/Adafruit_GrayOLED.cpp>
    -<Adafruit_GFX_Library/fontconvert/fontconvert.c>
    -<SSD1322/SSD1322.cpp>
    -<LiquidCrystalI2C/LiquidCrystalI2CEx.cpp>

[env]
framework = arduino
;platform = espressif32
;board = esp-wrover-kit

build_src_filter = ${common.build_src_filter}  ;с исключением лишних файлов флеш занят на 71,2% а без 72.0% = смысла в исключении нет, т.е. экономия только времени компиляции


;board_build.filesystem = littlefs  ;в этом проекте не пашет (Поддерживает каталоги)
;board_build.filesystem = SPIFFS    ;а с этим пашет (по умолчанию уже стоит) (Не поддерживает каталоги)
;upload_speed = 115200
upload_speed = 921600 ;115200 ;

monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0
monitor_filters = esp32_exception_decoder, time
monitor_echo = yes




;файл русского шрифта
;взять отсюда
; ...\yoRadio_Wrover_S3\src\fonts\glcdfont.c
;положить сюда
; ...\yoRadio_Wrover_S3\src\src\Adafruit_GFX_Library\glcdfont.c

;редактор тем для дисплея для файла mytheme.h
;https://vip-cxema.org/index.php/online-kalkulyatory/yoradio-redaktor-tem



;Полезные команды PlatformIO:
;bash (терминал)
;pio run --target clean   # сбросить кеш
;pio run                  # пересобрать

;pio run -t upload        # Загрузка кода
;pio run -t uploadfs      # Загрузка файлов в SPIFFS
;pio run -t monitor       # Монитор порта
;esptool erase_flash

;git commit -m "Ваше сообщение об изменениях"
;git add config_DevBoard_ESP32_S3-kit.ini