#ifndef myoptions_h
#define myoptions_h

/* Generated by myoptions.h generator - v0.7.8 */
/* https://e2002.github.io/docs/myoptions-generator.html?r=72,1,2,3,4,5,9,19,41,43,52,53,54,55,60,62&i=1,2,3,4,15,16,17,27,28,29,30,31,32,33,34&v=21,22,-1,32,25,27,26,14,36,34,39,35,33,13,4 */
/* Put this file next to yoRadio.ino and restart Arduino IDE. */

/* !!! Attention !!! */
/* This configuration depends on some additional libraries. Please install them using the library manager: */
/* Adafruit GFX Library, Adafruit ILI9341, OneButton, XPT2046_Touchscreen */

/* !!! Do not be alarmed, all right, the default values ​​are not included in this file !!! */

#define L10N_LANGUAGE			RU

#define DSP_MODEL			DSP_ILI9341

#define TFT_MISO 19
#define TFT_MOSI 23
#define TFT_CLK 18
#define LED_PIN 22
#define TFT_ROTATE 2

#define TFT_DC			4
#define TFT_CS			    5
#define BRIGHTNESS_PIN			22

#define VS1053_CS           255 // disable vs1053
#define I2S_DOUT			27
#define I2S_BCLK			26
#define I2S_LRC			    25

//#define BTN_MODE			14

#define ENC_BTNR			35
#define ENC_BTNL			33
#define ENC_BTNB			32
//#define ENC_INTERNALPULLUP	true
//#define ENC_HALFQUARD       false /*  (true, false, 255) Experiment  with it */

//#define ENC2_BTNR           33 // need external resistor for pullup
//#define ENC2_BTNL           35 // need external resistor for pullup
//#define ENC2_BTNB           32 // need external resistor for pullup
//#define ENC2_INTERNALPULLUP true
//#define ENC2_HALFQUARD      false          /*  Experiment  with it */

//#define TS_MODEL			TS_MODEL_XPT2046
//#define TS_CS			    4

/*  IR control  */
#define IR_PIN                15

// ex-options
#define VOLUME_STEP           1 // 1 is default
#define BUFLEN              190
#define BITRATE_FULL          1
#define VOLUME_LOGARITHMIC true // logarithmic volume change

#endif
